### ISSUE TITLE
Посмотри пакет strconv или что то такое.

### ISSUE THREAD

**Issue by korjavin** [plyul/go-course#2]
https://github.com/plyul/go-course/blob/458aed8d47e89ffabae803c843141bd386f33e39/stepik/1_13/1_13_1.go#L11

**Comment by plyul** [comment]
Я исходил из того, что, решая эту задачу, я ещё ничего не знаю про функции, пакеты, модули...

**Comment by korjavin** [comment]
Вообще, это всё даже не обязательно править.

Я тоже не ставлю цели каждую ошибку найти, я быстро пробегаюсь, если что то  в глаза бросается, то подсказываю.

Смотри на это просто как на hint, подсказку. 
Если ты про это уже знал, или думал - отлично, значит тут мысли совпадают.
