### ISSUE TITLE
Если бы эта функция имела название без insert мы бы не побоялись использовать её в других случаях. (naming)

### ISSUE THREAD

**Issue by korjavin** [plyul/go-course#6]
https://github.com/plyul/go-course/blob/10799a4747b0f559ed2fd1c2b8ce58ad7b110383/task2/sarray.go#L56

**Comment by plyul** [comment]
Понятное замечание. Изменено в https://github.com/plyul/go-course/commit/66120af05c0db2e1268e1edb5f52b2a878a821e8
